import Link from "next/link";

export default function OutputsPage() {
  return (
    <main className="command-shell">
      <section className="command-hero">
        <div>
          <p className="eyebrow">Output Center</p>
          <h1>Generated files and artifacts</h1>
          <p className="hero-copy">Use the automation page to run the worker and download files. This page is the central destination for filled PDFs, invoices, CSV, JSON, and logs.</p>
          <div className="hero-actions"><Link className="primary-link" href="/automation">Open Automation Runs</Link></div>
        </div>
      </section>
      <section className="command-grid">
        <div className="command-card"><p className="eyebrow">Filled PDFs</p><h2>Bid packets</h2><p>Generated by the worker from fetched PDFs.</p></div>
        <div className="command-card"><p className="eyebrow">Invoices</p><h2>Invoice drafts</h2><p>Print or save invoice PDFs from the invoice generator.</p></div>
        <div className="command-card"><p className="eyebrow">Logs</p><h2>Run history</h2><p>View automation execution details from the automation page.</p></div>
      </section>
    </main>
  );
}
